name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Run lint
        run: pnpm lint

      - name: Copy fake .env
        run: cp .env.example .env

      - name: Run build
        run: pnpm build
